graph BT
  cd8_naive_t_cell["CD8 Naive T Cell"]
  cd8_central_memory_t_cell["CD8 Central Memory T Cell"]
  cd8_effector_memory_t_cell["CD8 Effector Memory T Cell"]
  cd8_effector_memory_ra_t_cell["CD8 Effector Memory Ra T Cell"]
  cd8_tissue_resident_memory_t_cell["CD8 Tissue Resident Memory T Cell"]
  cd8_intraepithelial_lymphocyte["CD8 Intraepithelial Lymphocyte"]
  cd8_exhausted_t_cell["CD8 Exhausted T Cell"]
  cd4_naive_t_cell["CD4 Naive T Cell"]
  cd4_effector_memory_t_cell["CD4 Effector Memory T Cell"]
  cd4_effector_memory_ra_t_cell["CD4 Effector Memory Ra T Cell"]
  th1_like_t_cell["Th1 Like T Cell"]
  th17_cell["Th17 Cell"]
  follicular_helper_t_cell["Follicular Helper T Cell"]
  regulatory_t_cell["Regulatory T Cell"]
  mucosal_associated_invariant_t_cell["Mucosal Associated Invariant T Cell"]
  t_helper_1_like_cell["T Helper 1 Like Cell"]
  t_helper_17_cell["T Helper 17 Cell"]
  cd8_temra_cell["CD8 Temra Cell"]
  cd8_effector_t_cell["CD8 Effector T Cell"]
  intraepithelial_lymphocyte["Intraepithelial Lymphocyte"]
  cd4_memory_t_cell["CD4 Memory T Cell"]
  gnly_positive_cd4_t_cell["GNLY Positive CD4 T Cell"]
  tumor_infiltrating_t_cell["Tumor Infiltrating T Cell"]
  t_cell["T Cell"]
  cd8_positive_t_cell["CD8 Positive T Cell"]
  cd4_positive_t_cell["CD4 Positive T Cell"]
  chronically_stimulated_cd8_t_cell["Chronically Stimulated CD8 T Cell"]
  double_negative_t_cell["Double Negative T Cell"]
  double_positive_t_cell["Double Positive T Cell"]
  invariant_natural_killer_t_cell["Invariant Natural Killer T Cell"]
  proliferative_exhausted_cd8_t_cell["Proliferative Exhausted CD8 T Cell"]
  cd8_positive_cd4_negative_t_cell["CD8 Positive CD4 Negative T Cell"]
  cd4_positive_cd8_negative_t_cell["CD4 Positive CD8 Negative T Cell"]
  th1_like_cell["Th1 Like Cell"]
  proliferative_t_cell["Proliferative T Cell"]
  naive_t_cell["Naive T Cell"]
  effector_memory_t_cell["Effector Memory T Cell"]
  exhausted_t_cell["Exhausted T Cell"]
  cd8_positive_cd4_positive_t_cell["CD8 Positive CD4 Positive T Cell"]
  cd8_negative_cd4_negative_t_cell["CD8 Negative CD4 Negative T Cell"]
  cd8_t_cell["CD8 T Cell"]
  cd4_t_cell["CD4 T Cell"]
  cd8_temra_t_cell["CD8 Temra T Cell"]
  cd4_central_memory_t_cell["CD4 Central Memory T Cell"]
  cd4_temra_t_cell["CD4 Temra T Cell"]
  cd4_tissue_resident_memory_t_cell["CD4 Tissue Resident Memory T Cell"]
  peripheral_regulatory_t_cell["Peripheral Regulatory T Cell"]
  normal_regulatory_t_cell["Normal Regulatory T Cell"]
  tumor_regulatory_t_cell["Tumor Regulatory T Cell"]
  high_proliferative_cd8_exhausted_t_cell["High Proliferative CD8 Exhausted T Cell"]
  low_proliferative_cd8_exhausted_t_cell["Low Proliferative CD8 Exhausted T Cell"]
  conventional_cd8_t_cell["Conventional CD8 T Cell"]
  cd8_stem_like_t_cell["CD8 Stem Like T Cell"]
  proliferative_cd8_exhausted_t_cell["Proliferative CD8 Exhausted T Cell"]
  activated_cd4_t_cell["Activated CD4 T Cell"]
  cytotoxic_t_cell["Cytotoxic T Cell"]
  helper_t_cell["Helper T Cell"]
  ror_gamma_positive_regulatory_t_cell["Ror Gamma Positive Regulatory T Cell"]
  tumor_associated_macrophage["Tumor Associated Macrophage"]
  spp1_positive_tumor_associated_macrophage["SPP1 Positive Tumor Associated Macrophage"]
  cxcl10_positive_tumor_associated_macrophage["Cxcl10 Positive Tumor Associated Macrophage"]
  c1qc_positive_tumor_associated_macrophage["C1Qc Positive Tumor Associated Macrophage"]
  lyve1_positive_tumor_associated_macrophage["Lyve1 Positive Tumor Associated Macrophage"]
  proliferating_tumor_associated_macrophage["Proliferating Tumor Associated Macrophage"]
  macrophage_signature_tumor_associated_macrophage["Macrophage Signature Tumor Associated Macrophage"]
  monocyte["Monocyte"]
  cd16_positive_monocyte["Cd16 Positive Monocyte"]
  cd14_positive_monocyte["Cd14 Positive Monocyte"]
  neutrophil["Neutrophil"]
  dendritic_cell["Dendritic Cell"]
  th1_like_cd4_t_cell["Th1 Like CD4 T Cell"]
  natural_killer_cell["Natural Killer Cell"]
  b_cell["B Cell"]
  myeloid_derived_suppressor_cell["Myeloid Derived Suppressor Cell"]
  endothelial_cell["Endothelial Cell"]
  cancer_associated_fibroblast["Cancer Associated Fibroblast"]
  malignant_cell["Malignant Cell"]
  bone_marrow_derived_macrophage["Bone Marrow Derived Macrophage"]
  myeloid_cell["Myeloid Cell"]
  cancer_cell["Cancer Cell"]
  cd45_negative_cell["Cd45 Negative Cell"]
  naive_cd4_positive_t_cell["Naive CD4 Positive T Cell"]
  naive_cd8_positive_t_cell["Naive CD8 Positive T Cell"]
  macrophage["Macrophage"]
  stromal_cell["Stromal Cell"]
  colon_carcinoma_cell_line["Colon Carcinoma Cell Line"]
  spp1_positive_macrophage["SPP1 Positive Macrophage"]
  m1_macrophage["M1 Macrophage"]
  il1b_positive_macrophage["Il1B Positive Macrophage"]
  profibrotic_macrophage["Profibrotic Macrophage"]
  exhausted_cd8_t_cell["Exhausted CD8 T Cell"]
  conventional_cd4_t_cell["Conventional CD4 T Cell"]
  cytotoxic_t_lymphocyte["Cytotoxic T Lymphocyte"]
  tumor_cell["Tumor Cell"]
  thymic_stromal_cell["Thymic Stromal Cell"]
  naive_cd4_t_cell["Naive CD4 T Cell"]
  naive_cd8_t_cell["Naive CD8 T Cell"]
  th1_cell["Th1 Cell"]
  cytotoxic_cd8_t_cell["Cytotoxic CD8 T Cell"]
  lung_carcinoma_cell_line["Lung Carcinoma Cell Line"]
  m2_macrophage["M2 Macrophage"]
  unpolarized_macrophage["Unpolarized Macrophage"]
  th1_cd4_t_cell["Th1 CD4 T Cell"]
  immune_cell["Immune Cell"]

  cd8_naive_t_cell --> cd8_t_cell
  cd8_central_memory_t_cell --> cd8_t_cell
  cd8_effector_memory_t_cell --> cd8_t_cell
  cd8_effector_memory_ra_t_cell --> cd8_t_cell
  cd8_tissue_resident_memory_t_cell --> cd8_t_cell
  cd8_intraepithelial_lymphocyte --> cd8_t_cell
  cd8_exhausted_t_cell --> cd8_t_cell
  cd4_naive_t_cell --> cd4_t_cell
  cd4_effector_memory_t_cell --> cd4_t_cell
  cd4_effector_memory_ra_t_cell --> cd4_t_cell
  th1_like_t_cell --> cd4_t_cell
  th17_cell --> cd4_t_cell
  follicular_helper_t_cell --> cd4_t_cell
  regulatory_t_cell --> cd4_t_cell
  mucosal_associated_invariant_t_cell --> t_cell
  t_helper_1_like_cell --> cd4_t_cell
  t_helper_17_cell --> cd4_t_cell
  cd8_temra_cell --> cd8_t_cell
  cd8_effector_t_cell --> cd8_t_cell
  intraepithelial_lymphocyte --> t_cell
  cd4_memory_t_cell --> cd4_t_cell
  gnly_positive_cd4_t_cell --> cd4_t_cell
  tumor_infiltrating_t_cell --> t_cell
  cd8_positive_t_cell --> t_cell
  cd4_positive_t_cell --> t_cell
  chronically_stimulated_cd8_t_cell --> cd8_positive_t_cell
  double_negative_t_cell --> t_cell
  double_positive_t_cell --> t_cell
  invariant_natural_killer_t_cell --> t_cell
  proliferative_exhausted_cd8_t_cell --> cd8_positive_t_cell
  cd8_positive_cd4_negative_t_cell --> t_cell
  cd4_positive_cd8_negative_t_cell --> t_cell
  th1_like_cell --> cd4_positive_cd8_negative_t_cell
  proliferative_t_cell --> t_cell
  naive_t_cell --> t_cell
  effector_memory_t_cell --> t_cell
  exhausted_t_cell --> t_cell
  cd8_positive_cd4_positive_t_cell --> t_cell
  cd8_negative_cd4_negative_t_cell --> t_cell
  cd8_temra_t_cell --> cd8_t_cell
  cd4_central_memory_t_cell --> cd4_t_cell
  cd4_temra_t_cell --> cd4_t_cell
  cd4_tissue_resident_memory_t_cell --> cd4_t_cell
  peripheral_regulatory_t_cell --> regulatory_t_cell
  normal_regulatory_t_cell --> regulatory_t_cell
  tumor_regulatory_t_cell --> regulatory_t_cell
  high_proliferative_cd8_exhausted_t_cell --> cd8_exhausted_t_cell
  low_proliferative_cd8_exhausted_t_cell --> cd8_exhausted_t_cell
  conventional_cd8_t_cell --> cd8_t_cell
  cd8_stem_like_t_cell --> cd8_t_cell
  proliferative_cd8_exhausted_t_cell --> cd8_exhausted_t_cell
  activated_cd4_t_cell --> cd4_t_cell
  cytotoxic_t_cell --> t_cell
  helper_t_cell --> t_cell
  ror_gamma_positive_regulatory_t_cell --> regulatory_t_cell
  tumor_associated_macrophage --> macrophage
  spp1_positive_tumor_associated_macrophage --> tumor_associated_macrophage
  cxcl10_positive_tumor_associated_macrophage --> tumor_associated_macrophage
  c1qc_positive_tumor_associated_macrophage --> tumor_associated_macrophage
  lyve1_positive_tumor_associated_macrophage --> tumor_associated_macrophage
  proliferating_tumor_associated_macrophage --> tumor_associated_macrophage
  macrophage_signature_tumor_associated_macrophage --> tumor_associated_macrophage
  monocyte --> myeloid_cell
  cd16_positive_monocyte --> monocyte
  cd14_positive_monocyte --> monocyte
  neutrophil --> myeloid_cell
  dendritic_cell --> myeloid_cell
  th1_like_cd4_t_cell --> cd4_positive_t_cell
  myeloid_derived_suppressor_cell --> myeloid_cell
  endothelial_cell --> stromal_cell
  cancer_associated_fibroblast --> stromal_cell
  bone_marrow_derived_macrophage --> macrophage
  naive_cd4_positive_t_cell --> cd4_positive_t_cell
  naive_cd8_positive_t_cell --> cd8_positive_t_cell
  macrophage --> myeloid_cell
  spp1_positive_macrophage --> tumor_associated_macrophage
  m1_macrophage --> macrophage
  il1b_positive_macrophage --> tumor_associated_macrophage
  profibrotic_macrophage --> macrophage
  exhausted_cd8_t_cell --> cd8_t_cell
  conventional_cd4_t_cell --> cd4_t_cell
  cytotoxic_t_lymphocyte --> cd8_t_cell
  thymic_stromal_cell --> stromal_cell
  naive_cd4_t_cell --> t_cell
  naive_cd8_t_cell --> t_cell
  th1_cell --> cd4_t_cell
  cytotoxic_cd8_t_cell --> cd8_t_cell
  lung_carcinoma_cell_line --> tumor_cell
  m2_macrophage --> macrophage
  unpolarized_macrophage --> macrophage
  th1_cd4_t_cell --> cd4_t_cell
